package models;
// default package
// Generated Apr 11, 2016 2:03:20 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

import static javax.persistence.GenerationType.SEQUENCE;

/**
 * Item generated by hbm2java
 */
@Entity
public class Item {

	@Id
	@SequenceGenerator(name="seq_item", sequenceName="seq_item_seq"
					  , allocationSize=1)
	@GeneratedValue(strategy=SEQUENCE, generator="seq_item")
	@Column(name = "id_item", unique = true, nullable = false)
	private int idItem;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_carro", nullable = false)
	private Carro carro;
	
	@ManyToOne
	@JoinColumn(name="pedido")
	@JsonBackReference
	private Pedido pedido;
	
	@Column(name = "valor", nullable = false, precision = 20, scale = 5)
	private BigDecimal valor;
	
	@Column(name = "desconto", nullable = false, precision = 20, scale = 5)
	private BigDecimal desconto;

	public Item() {}

	public Item(int idItem, Carro carro, Pedido pedido, BigDecimal valor, BigDecimal desconto) {
		this.idItem = idItem;
		this.carro = carro;
		//this.pedido = pedido;
		this.valor = valor;
		this.desconto = desconto;
	}

	public int getIdItem() {
		return this.idItem;
	}

	public void setIdItem(int idItem) {
		this.idItem = idItem;
	}

	public Carro getCarro() {
		return this.carro;
	}

	public void setCarro(Carro carro) {
		this.carro = carro;
	}

	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public BigDecimal getDesconto() {
		return this.desconto;
	}

	public void setDesconto(BigDecimal desconto) {
		this.desconto = desconto;
	}

}
