package models;
// default package
// Generated Apr 11, 2016 2:03:20 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import static javax.persistence.GenerationType.SEQUENCE;
/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", schema = "public")
public class Pedido {

	@Id
	@GeneratedValue(strategy=SEQUENCE, generator="seq_pedido")
	@SequenceGenerator(name="seq_pedido", sequenceName="seq_pedido_seq")
	//@Column(name = "id_pedido", unique = true, nullable = false)
	private int idPedido;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_atendente", nullable = false)
	private Atendente atendente;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cliente", nullable = false)
	@JsonBackReference
	private Cliente cliente;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_entrega", nullable = false, length = 29)	
	private Date dataEntrega;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_locacao", nullable = false, length = 29)
	private Date dataLocacao;
	
	@Column(name = "total", nullable = false, precision = 20, scale = 5)
	private BigDecimal total;
	
	@OneToMany(mappedBy="pedido", fetch = FetchType.EAGER)
	@JsonManagedReference
	private List<Item> items;

	public Pedido() {}

	/*public Pedido(int idPedido, Atendente atendente, Cliente cliente, Date dataEntrega, Date dataLocacao,
			BigDecimal total) {
		this.idPedido = idPedido;
		this.atendente = atendente;
		this.cliente = cliente;
		this.dataEntrega = dataEntrega;
		this.dataLocacao = dataLocacao;
		this.total = total;
	}*/

	public Pedido(int idPedido, Atendente atendente, Cliente cliente, Date dataEntrega, Date dataLocacao,
			BigDecimal total, List<Item> items) {
		this.idPedido = idPedido;
		this.atendente = atendente;
		this.cliente = cliente;
		this.dataEntrega = dataEntrega;
		this.dataLocacao = dataLocacao;
		this.total = total;
		this.items = items;
	}

	public int getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(int idPedido) {
		this.idPedido = idPedido;
	}

	public Atendente getAtendente() {
		return this.atendente;
	}

	public void setAtendente(Atendente atendente) {
		this.atendente = atendente;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Date getDataEntrega() {
		return this.dataEntrega;
	}

	public void setDataEntrega(Date dataEntrega) {
		this.dataEntrega = dataEntrega;
	}

	public Date getDataLocacao() {
		return this.dataLocacao;
	}

	public void setDataLocacao(Date dataLocacao) {
		this.dataLocacao = dataLocacao;
	}

	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	public List<Item> getItems() {
		return this.items;
	}

	public void setItems(List<Item> items) {
		this.items = items;
	}

}
